// Generated by slate-generator. Do not edit.

@preconcurrency import CoreData
import Foundation
import SlateFixturePatientModels
import Slate
import SlateSchema

@objc(DatabasePatient)
public final class DatabasePatient: NSManagedObject {
    public static let slateEntityName = "Patient"

    @nonobjc public class func fetchRequest() -> NSFetchRequest<DatabasePatient> {
        NSFetchRequest<DatabasePatient>(entityName: slateEntityName)
    }

    public static func create(in context: NSManagedObjectContext) -> DatabasePatient {
        guard let entity = NSEntityDescription.entity(forEntityName: slateEntityName, in: context) else {
            fatalError("Missing Core Data entity: \(slateEntityName)")
        }
        return DatabasePatient(entity: entity, insertInto: context)
    }

    @NSManaged public var patientId: String

    @NSManaged public var firstName: String

    @NSManaged public var lastName: String

    public var age: Int? {
        get {
            willAccessValue(forKey: "age")
            defer { didAccessValue(forKey: "age") }
            return (primitiveValue(forKey: "age") as? NSNumber)?.intValue
        }
        set {
            willChangeValue(forKey: "age")
            defer { didChangeValue(forKey: "age") }
            setPrimitiveValue(newValue.map { NSNumber(value: $0) }, forKey: "age")
        }
    }

    public var status: Patient.Status {
        get {
            willAccessValue(forKey: "status")
            defer { didAccessValue(forKey: "status") }
            let raw = primitiveValue(forKey: "status") as? String
            return raw.flatMap { Patient.Status(rawValue: $0) } ?? Patient.Status.active
        }
        set {
            willChangeValue(forKey: "status")
            defer { didChangeValue(forKey: "status") }
            setPrimitiveValue(newValue.rawValue, forKey: "status")
        }
    }

    @NSManaged public var address_has: Bool

    @NSManaged public var address_line1: String?

    @NSManaged public var address_city: String?

    @NSManaged public var zip: String?
    @NSManaged public var notes: NSOrderedSet?
}
