// Generated by slate-generator. Do not edit.

@preconcurrency import CoreData
import Foundation
import SlateFixturePatientModels
import Slate
import SlateSchema

extension DatabasePatient: Patient.ManagedPropertyProviding {
    public var address: Patient.Address? {
        guard address_has else {
            return nil
        }
        return Patient.Address(
            line1: address_line1,
            city: address_city,
            postalCode: zip
        )
    }
}

extension DatabasePatient: SlateMutableObject {
    public typealias ImmutableObject = Patient

    public var slateObject: Patient {
        Patient(managedObject: self)
    }
}

extension DatabasePatient: SlateRelationshipHydratingMutableObject {
    public func slateObject(hydrating relationships: Set<String>) throws -> Patient {
            let resolvedStatus: Patient.Status = (primitiveValue(forKey: "status") as? String).flatMap { Patient.Status(rawValue: $0) } ?? Patient.Status.active
    return Patient(
                slateID: objectID,
                patientId: patientId,
                firstName: firstName,
                lastName: lastName,
                age: age,
                status: resolvedStatus,
                address: address,
                notes: relationships.contains("notes") ? (notes?.array as? [DatabasePatientNote])?.map(\.slateObject) : nil
        )
    }
}
