// Generated by slate-generator. Do not edit.

@preconcurrency import CoreData
import Foundation
import SlateFixturePatientModels
import Slate
import SlateSchema

// This file was autogenerated by Slate
// Check your project documentation for how to autogenerate Slate files

extension DatabasePatientNote: PatientNote.ManagedPropertyProviding {

}

extension DatabasePatientNote: SlateMutableObject {
    public typealias ImmutableObject = PatientNote

    public var slateObject: PatientNote {
        PatientNote(managedObject: self)
    }
}

extension DatabasePatientNote: SlateRelationshipHydratingMutableObject {
    public func slateObject(hydrating relationships: Set<String>) throws -> PatientNote {
    return PatientNote(
                slateID: objectID,
                noteId: noteId,
                body: body,
                patient: relationships.contains("patient") ? patient?.slateObject : nil
        )
    }
}
