// Generated by slate-generator. Do not edit.

@preconcurrency import CoreData
import Foundation
import SlateFixturePatientModels
import Slate
import SlateSchema

public enum PatientSlateSchema: SlateSchema {
    public static let schemaIdentifier = "PatientSlateSchema"
    public static let schemaFingerprint = "diagnostic:49f19c9bec78d5fb"

    public static let entities: [SlateEntityMetadata] = [
        SlateEntityMetadata(
            immutableTypeName: "Patient",
            mutableTypeName: "DatabasePatient",
            entityName: "Patient",
            attributes: [
        SlateAttributeMetadata(
            swiftName: "patientId",
            storageName: "patientId",
            swiftType: "String",
            storageType: "string",
            optional: false,
            indexed: false
        ),
        SlateAttributeMetadata(
            swiftName: "firstName",
            storageName: "firstName",
            swiftType: "String",
            storageType: "string",
            optional: false,
            indexed: false
        ),
        SlateAttributeMetadata(
            swiftName: "lastName",
            storageName: "lastName",
            swiftType: "String",
            storageType: "string",
            optional: false,
            indexed: false
        ),
        SlateAttributeMetadata(
            swiftName: "age",
            storageName: "age",
            swiftType: "Int?",
            storageType: "integer64",
            optional: true,
            indexed: false
        ),
        SlateAttributeMetadata(
            swiftName: "status",
            storageName: "status",
            swiftType: "Status",
            storageType: "string",
            optional: false,
            indexed: false
        ),
        SlateAttributeMetadata(
            swiftName: "address_has",
            storageName: "address_has",
            swiftType: "Bool",
            storageType: "boolean",
            optional: false,
            indexed: false
        ),
        SlateAttributeMetadata(
            swiftName: "address_line1",
            storageName: "address_line1",
            swiftType: "String?",
            storageType: "string",
            optional: true,
            indexed: false
        ),
        SlateAttributeMetadata(
            swiftName: "address_city",
            storageName: "address_city",
            swiftType: "String?",
            storageType: "string",
            optional: true,
            indexed: false
        ),
        SlateAttributeMetadata(
            swiftName: "address_postalCode",
            storageName: "zip",
            swiftType: "String?",
            storageType: "string",
            optional: true,
            indexed: false
        )
            ],
            relationships: [
        SlateRelationshipMetadata(
            name: "notes",
            kind: .toMany,
            destination: "PatientNote",
            inverse: "patient",
            deleteRule: .cascade,
            ordered: true
        )
            ]
        ),
        SlateEntityMetadata(
            immutableTypeName: "PatientNote",
            mutableTypeName: "DatabasePatientNote",
            entityName: "PatientNote",
            attributes: [
        SlateAttributeMetadata(
            swiftName: "noteId",
            storageName: "noteId",
            swiftType: "String",
            storageType: "string",
            optional: false,
            indexed: false
        ),
        SlateAttributeMetadata(
            swiftName: "body",
            storageName: "body",
            swiftType: "String",
            storageType: "string",
            optional: false,
            indexed: false
        )
            ],
            relationships: [
        SlateRelationshipMetadata(
            name: "patient",
            kind: .toOne,
            destination: "Patient",
            inverse: "notes",
            deleteRule: .nullify,
            ordered: false
        )
            ]
        )
    ]

    public static func makeManagedObjectModel() throws -> NSManagedObjectModel {
                let patientPatientIdAttribute = NSAttributeDescription()
                patientPatientIdAttribute.name = "patientId"
                patientPatientIdAttribute.attributeType = .stringAttributeType
                patientPatientIdAttribute.isOptional = false

                let patientFirstNameAttribute = NSAttributeDescription()
                patientFirstNameAttribute.name = "firstName"
                patientFirstNameAttribute.attributeType = .stringAttributeType
                patientFirstNameAttribute.isOptional = false

                let patientLastNameAttribute = NSAttributeDescription()
                patientLastNameAttribute.name = "lastName"
                patientLastNameAttribute.attributeType = .stringAttributeType
                patientLastNameAttribute.isOptional = false

                let patientAgeAttribute = NSAttributeDescription()
                patientAgeAttribute.name = "age"
                patientAgeAttribute.attributeType = .integer64AttributeType
                patientAgeAttribute.isOptional = true

                let patientStatusAttribute = NSAttributeDescription()
                patientStatusAttribute.name = "status"
                patientStatusAttribute.attributeType = .stringAttributeType
                patientStatusAttribute.isOptional = false
                patientStatusAttribute.defaultValue = Patient.Status.active.rawValue

                let patientAddress_hasAttribute = NSAttributeDescription()
                patientAddress_hasAttribute.name = "address_has"
                patientAddress_hasAttribute.attributeType = .booleanAttributeType
                patientAddress_hasAttribute.isOptional = false

                let patientAddress_line1Attribute = NSAttributeDescription()
                patientAddress_line1Attribute.name = "address_line1"
                patientAddress_line1Attribute.attributeType = .stringAttributeType
                patientAddress_line1Attribute.isOptional = true

                let patientAddress_cityAttribute = NSAttributeDescription()
                patientAddress_cityAttribute.name = "address_city"
                patientAddress_cityAttribute.attributeType = .stringAttributeType
                patientAddress_cityAttribute.isOptional = true

                let patientAddress_postalCodeAttribute = NSAttributeDescription()
                patientAddress_postalCodeAttribute.name = "zip"
                patientAddress_postalCodeAttribute.attributeType = .stringAttributeType
                patientAddress_postalCodeAttribute.isOptional = true

                let patientEntity = NSEntityDescription()
                patientEntity.name = "Patient"
                patientEntity.managedObjectClassName = NSStringFromClass(DatabasePatient.self)
                patientEntity.properties = [patientPatientIdAttribute, patientFirstNameAttribute, patientLastNameAttribute, patientAgeAttribute, patientStatusAttribute, patientAddress_hasAttribute, patientAddress_line1Attribute, patientAddress_cityAttribute, patientAddress_postalCodeAttribute]



                let patientNoteNoteIdAttribute = NSAttributeDescription()
                patientNoteNoteIdAttribute.name = "noteId"
                patientNoteNoteIdAttribute.attributeType = .stringAttributeType
                patientNoteNoteIdAttribute.isOptional = false

                let patientNoteBodyAttribute = NSAttributeDescription()
                patientNoteBodyAttribute.name = "body"
                patientNoteBodyAttribute.attributeType = .stringAttributeType
                patientNoteBodyAttribute.isOptional = false

                let patientNoteEntity = NSEntityDescription()
                patientNoteEntity.name = "PatientNote"
                patientNoteEntity.managedObjectClassName = NSStringFromClass(DatabasePatientNote.self)
                patientNoteEntity.properties = [patientNoteNoteIdAttribute, patientNoteBodyAttribute]


        let patientNotesRelationship = NSRelationshipDescription()
        patientNotesRelationship.name = "notes"
        patientNotesRelationship.destinationEntity = patientNoteEntity
        patientNotesRelationship.deleteRule = .cascadeDeleteRule
        patientNotesRelationship.isOptional = true
        patientNotesRelationship.isOrdered = true
        patientNotesRelationship.minCount = 0
        patientNotesRelationship.maxCount = 0

        let patientNotePatientRelationship = NSRelationshipDescription()
        patientNotePatientRelationship.name = "patient"
        patientNotePatientRelationship.destinationEntity = patientEntity
        patientNotePatientRelationship.deleteRule = .nullifyDeleteRule
        patientNotePatientRelationship.isOptional = false
        patientNotePatientRelationship.isOrdered = false
        patientNotePatientRelationship.minCount = 1
        patientNotePatientRelationship.maxCount = 1

        patientNotesRelationship.inverseRelationship = patientNotePatientRelationship
        patientNotePatientRelationship.inverseRelationship = patientNotesRelationship

        patientEntity.properties = [patientPatientIdAttribute, patientFirstNameAttribute, patientLastNameAttribute, patientAgeAttribute, patientStatusAttribute, patientAddress_hasAttribute, patientAddress_line1Attribute, patientAddress_cityAttribute, patientAddress_postalCodeAttribute, patientNotesRelationship]
        patientNoteEntity.properties = [patientNoteNoteIdAttribute, patientNoteBodyAttribute, patientNotePatientRelationship]

        let model = NSManagedObjectModel()
        model.entities = [
            patientEntity,
            patientNoteEntity
        ]
        return model
    }

    public static func registerTables(_ registry: inout SlateTableRegistry) {
        registry.register(
            immutable: Patient.self,
            mutable: DatabasePatient.self,
            entityName: "Patient",
            uniquenessConstraints: []
        )
        registry.register(
            immutable: PatientNote.self,
            mutable: DatabasePatientNote.self,
            entityName: "PatientNote",
            uniquenessConstraints: []
        )
    }
}
