// Generated by slate-generator. Do not edit.

@preconcurrency import CoreData
import Foundation
import SlateFixturePatientModels
import Slate
import SlateSchema

// This file was autogenerated by Slate
// Check your project documentation for how to autogenerate Slate files

@objc(DatabasePatientNote)
public final class DatabasePatientNote: NSManagedObject {
    public static let slateEntityName = "PatientNote"

    @nonobjc public class func fetchRequest() -> NSFetchRequest<DatabasePatientNote> {
        NSFetchRequest<DatabasePatientNote>(entityName: slateEntityName)
    }

    public static func create(in context: NSManagedObjectContext) -> DatabasePatientNote {
        guard let entity = NSEntityDescription.entity(forEntityName: slateEntityName, in: context) else {
            fatalError("Missing Core Data entity: \(slateEntityName)")
        }
        return DatabasePatientNote(entity: entity, insertInto: context)
    }

    @NSManaged public var noteId: String

    @NSManaged public var body: String
    @NSManaged public var patient: DatabasePatient?
}
