import Foundation

/// Renders the human-facing `CloudKitFieldsReport.md` for a CloudKit schema.
///
/// The report enumerates, per record type, the fields Slate expects to appear
/// in CloudKit — including the synthesized `*_has` embedded-presence booleans and
/// the flattened embedded value fields — plus each relationship as a CloudKit
/// reference. Its sole consumer is a developer reconciling the CloudKit dashboard
/// by hand, so it is Markdown rather than JSON. A `schemaFingerprint` header line
/// pins the report to the generation it documents.
///
/// The renderer (`GeneratedSchemaRenderer`) emits this file only for CloudKit
/// schemas and registers it in the manifest, so `check` drift-detects it and
/// `clean`/`--prune` track it.
public struct CloudKitFieldsReport: Sendable {
    public init() {}

    public func render(schema: NormalizedSchema) -> String {
        var sections: [String] = [header(schema: schema)]
        for entity in schema.entities {
            sections.append(renderEntity(entity))
        }
        // Trailing newline so the committed file ends cleanly.
        return sections.joined(separator: "\n\n") + "\n"
    }

    // MARK: - Sections

    private func header(schema: NormalizedSchema) -> String {
        """
        # CloudKit Fields Report

        > Auto-generated by Slate. Do not edit.

        Schema fingerprint: `\(schema.schemaFingerprint)`

        This report enumerates the CloudKit record types and fields Slate expects \
        for this schema, so the CloudKit dashboard can be reconciled by hand. The \
        `Asset` column is advisory: `NSPersistentCloudKitContainer` chooses `CKAsset` \
        versus inline `Bytes` by runtime value size against Core Data's \
        externalization threshold, not statically from the flag.
        """
    }

    private func renderEntity(_ entity: NormalizedEntity) -> String {
        var lines: [String] = [
            "## \(entity.entityName) (record type)",
            "",
            "| Field | CK type | Optional | Default | Asset |",
            "| --- | --- | --- | --- | --- |",
        ]

        for attribute in storageAttributes(for: entity) {
            let asset = attribute.externalStorage ? "may mirror as `CKAsset`" : "—"
            lines.append(
                "| `\(attribute.storageName)` | `\(ckRecordType(for: attribute.storageType))`"
                    + " | \(yesNo(attribute.optional)) | \(yesNo(hasDefault(attribute)))"
                    + " | \(asset) |"
            )
        }

        if !entity.relationships.isEmpty {
            lines.append("")
            lines.append("Relationships:")
            lines.append("")
            for relationship in entity.relationships {
                let cardinality = relationship.kind == "toOne" ? "to-one" : "to-many"
                lines.append(
                    "- `\(relationship.name)` → `\(relationship.destination)`"
                        + " (\(cardinality) CloudKit reference)"
                )
            }
        }

        return lines.joined(separator: "\n")
    }

    // MARK: - Field synthesis

    /// Mirrors `GeneratedSchemaRenderer.storageAttributes(for:)`: the top-level
    /// attributes plus, per embedded value, the synthesized `*_has` presence
    /// boolean (defaulted `false` in CloudKit mode) and the flattened (always
    /// optional) embedded value fields. The report documents the same field set
    /// the model emits.
    private func storageAttributes(for entity: NormalizedEntity) -> [NormalizedAttribute] {
        entity.attributes + entity.embedded.flatMap { embedded in
            let presence = embedded.presenceStorageName.map { storageName in
                NormalizedAttribute(
                    swiftName: storageName,
                    storageName: storageName,
                    swiftType: "Bool",
                    storageType: "boolean",
                    optional: false,
                    defaultExpression: entity.cloudKit ? "false" : nil
                )
            }
            return [presence].compactMap { $0 } + embedded.attributes.map { attribute in
                NormalizedAttribute(
                    swiftName: "\(embedded.swiftName)_\(attribute.swiftName)",
                    storageName: attribute.storageName,
                    swiftType: attribute.optional ? attribute.swiftType : "\(attribute.swiftType)?",
                    storageType: attribute.storageType,
                    optional: true,
                    indexed: attribute.indexed,
                    externalStorage: attribute.externalStorage
                )
            }
        }
    }

    // MARK: - Mappings

    /// Maps a Slate storage type to the CloudKit record value type a developer
    /// will see in the dashboard.
    private func ckRecordType(for storageType: String) -> String {
        switch storageType {
        case "string", "uri", "uuid", "rawRepresentable":
            "String"
        case "boolean", "integer16", "integer32", "integer64":
            "Int64"
        case "float", "double", "decimal":
            "Double"
        case "date":
            "Date/Timestamp"
        case "binary":
            "Bytes"
        default:
            storageType
        }
    }

    private func hasDefault(_ attribute: NormalizedAttribute) -> Bool {
        guard let raw = attribute.defaultExpression?.trimmingCharacters(in: .whitespacesAndNewlines) else {
            return false
        }
        return !raw.isEmpty && raw != "nil"
    }

    private func yesNo(_ value: Bool) -> String {
        value ? "Yes" : "No"
    }
}
