import Foundation

public struct GeneratedSchemaRenderer: Sendable {
    public init() {}

    public func render(schema: NormalizedSchema) -> [GeneratedFile] {
        let entityFiles = schema.entities.map { entity in
            GeneratedFile(
                path: "\(entity.mutableName).swift",
                contents: renderMutableObject(entity: entity, schema: schema),
                kind: .mutable
            )
        }

        let bridgeFiles = schema.entities.map { entity in
            GeneratedFile(
                path: "\(entity.swiftName)+SlateBridge.swift",
                contents: renderBridge(entity: entity, schema: schema),
                kind: .bridge
            )
        }

        let schemaFile = GeneratedFile(
            path: "\(schema.schemaName).swift",
            contents: renderSchema(schema),
            kind: .schema
        )

        let manifest = GenerationManifest(
            schemaFingerprint: schema.schemaFingerprint,
            files: (entityFiles + bridgeFiles + [schemaFile]).map(\.path).sorted()
        )

        let manifestFile = GeneratedFile(
            path: "SlateGenerationManifest.json",
            contents: renderManifest(manifest),
            kind: .manifest
        )

        return (entityFiles + bridgeFiles + [schemaFile, manifestFile])
            .sorted { $0.path < $1.path }
    }

    public func renderManifest(_ manifest: GenerationManifest) -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let data = (try? encoder.encode(manifest)) ?? Data()
        return String(decoding: data, as: UTF8.self) + "\n"
    }

    private func renderMutableObject(entity: NormalizedEntity, schema: NormalizedSchema) -> String {
        let propertyLines = storageAttributes(for: entity).map { attribute in
            renderMutableAttribute(attribute: attribute, entity: entity)
        }.joined(separator: "\n\n")
        let relationshipProperties = renderMutableRelationshipProperties(entity: entity, schema: schema)

        return """
        // Generated by slate-generator. Do not edit.

        @preconcurrency import CoreData
        import Foundation
        import \(schema.modelModule)
        import Slate
        import SlateSchema

        @objc(\(entity.mutableName))
        public final class \(entity.mutableName): NSManagedObject {
            public static let slateEntityName = "\(entity.entityName)"

            @nonobjc public class func fetchRequest() -> NSFetchRequest<\(entity.mutableName)> {
                NSFetchRequest<\(entity.mutableName)>(entityName: slateEntityName)
            }

            public static func create(in context: NSManagedObjectContext) -> \(entity.mutableName) {
                guard let entity = NSEntityDescription.entity(forEntityName: slateEntityName, in: context) else {
                    fatalError("Missing Core Data entity: \\(slateEntityName)")
                }
                return \(entity.mutableName)(entity: entity, insertInto: context)
            }

        \(propertyLines)
        \(relationshipProperties)
        }

        """
    }

    private func renderMutableAttribute(attribute: NormalizedAttribute, entity: NormalizedEntity) -> String {
        if let enumKind = attribute.enumKind {
            return renderEnumMutableAccessor(attribute: attribute, enumKind: enumKind, entity: entity)
        }
        if attribute.optional, let bridge = numericBoolBridge(for: attribute) {
            return renderOptionalNumericAccessor(attribute: attribute, bridge: bridge)
        }
        return "    @NSManaged public var \(attribute.storageName): \(managedSwiftType(for: attribute))"
    }

    /// Bridge metadata for optional numeric / bool / decimal attributes.
    /// Core Data stores these as `NSNumber`/`NSDecimalNumber`; @NSManaged
    /// with a Swift optional scalar does not bridge correctly, so we
    /// generate a `primitiveValue`-backed accessor instead.
    private struct NumericBoolBridge {
        let swiftType: String  // e.g., "Int", "Bool", "Decimal"
        let nsBoxType: String  // "NSNumber" or "NSDecimalNumber"
        let nsAccessor: String // ".intValue", ".decimalValue", etc.
        let nsInit: (String) -> String
    }

    private func numericBoolBridge(for attribute: NormalizedAttribute) -> NumericBoolBridge? {
        switch attribute.storageType {
        case "boolean":
            return NumericBoolBridge(
                swiftType: "Bool",
                nsBoxType: "NSNumber",
                nsAccessor: ".boolValue",
                nsInit: { "NSNumber(value: \($0))" }
            )
        case "integer16":
            return NumericBoolBridge(
                swiftType: "Int16",
                nsBoxType: "NSNumber",
                nsAccessor: ".int16Value",
                nsInit: { "NSNumber(value: \($0))" }
            )
        case "integer32":
            return NumericBoolBridge(
                swiftType: "Int32",
                nsBoxType: "NSNumber",
                nsAccessor: ".int32Value",
                nsInit: { "NSNumber(value: \($0))" }
            )
        case "integer64":
            // Cover both `Int` and `Int64` — both map to integer64 storage
            // but the immutable Swift type differs.
            let swiftType = unwrappedSwiftType(attribute.swiftType)
            let accessor = swiftType == "Int" ? ".intValue" : ".int64Value"
            return NumericBoolBridge(
                swiftType: swiftType,
                nsBoxType: "NSNumber",
                nsAccessor: accessor,
                nsInit: { "NSNumber(value: \($0))" }
            )
        case "float":
            return NumericBoolBridge(
                swiftType: "Float",
                nsBoxType: "NSNumber",
                nsAccessor: ".floatValue",
                nsInit: { "NSNumber(value: \($0))" }
            )
        case "double":
            return NumericBoolBridge(
                swiftType: "Double",
                nsBoxType: "NSNumber",
                nsAccessor: ".doubleValue",
                nsInit: { "NSNumber(value: \($0))" }
            )
        case "decimal":
            return NumericBoolBridge(
                swiftType: "Decimal",
                nsBoxType: "NSDecimalNumber",
                nsAccessor: ".decimalValue",
                nsInit: { "NSDecimalNumber(decimal: \($0))" }
            )
        default:
            return nil
        }
    }

    private func unwrappedSwiftType(_ swiftType: String) -> String {
        if swiftType.hasSuffix("?") {
            return String(swiftType.dropLast())
        }
        return swiftType
    }

    private func renderOptionalNumericAccessor(
        attribute: NormalizedAttribute,
        bridge: NumericBoolBridge
    ) -> String {
        let storageKey = attribute.storageName
        let initExpression = bridge.nsInit("$0")
        return """
            public var \(attribute.swiftName): \(bridge.swiftType)? {
                get {
                    willAccessValue(forKey: "\(storageKey)")
                    defer { didAccessValue(forKey: "\(storageKey)") }
                    return (primitiveValue(forKey: "\(storageKey)") as? \(bridge.nsBoxType))?\(bridge.nsAccessor)
                }
                set {
                    willChangeValue(forKey: "\(storageKey)")
                    defer { didChangeValue(forKey: "\(storageKey)") }
                    setPrimitiveValue(newValue.map { \(initExpression) }, forKey: "\(storageKey)")
                }
            }
        """
    }

    private func renderEnumMutableAccessor(
        attribute: NormalizedAttribute,
        enumKind: NormalizedEnumKind,
        entity: NormalizedEntity
    ) -> String {
        let qualifiedEnum = "\(entity.swiftName).\(enumKind.typeName)"
        let storageKey = attribute.storageName
        let rawType = enumKind.rawType
        let primitiveAccess = "primitiveValue(forKey: \"\(storageKey)\")"

        if attribute.optional {
            return """
                public var \(attribute.swiftName): \(qualifiedEnum)? {
                    get {
                        willAccessValue(forKey: "\(storageKey)")
                        defer { didAccessValue(forKey: "\(storageKey)") }
                        guard let raw = \(primitiveAccess) as? \(rawType) else {
                            return nil
                        }
                        return \(qualifiedEnum)(rawValue: raw)
                    }
                    set {
                        willChangeValue(forKey: "\(storageKey)")
                        defer { didChangeValue(forKey: "\(storageKey)") }
                        setPrimitiveValue(newValue?.rawValue, forKey: "\(storageKey)")
                    }
                }
            """
        }

        let fallback = enumDefaultFallback(for: attribute, enumKind: enumKind, entity: entity)
        return """
            public var \(attribute.swiftName): \(qualifiedEnum) {
                get {
                    willAccessValue(forKey: "\(storageKey)")
                    defer { didAccessValue(forKey: "\(storageKey)") }
                    let raw = \(primitiveAccess) as? \(rawType)
                    return raw.flatMap { \(qualifiedEnum)(rawValue: $0) } ?? \(fallback)
                }
                set {
                    willChangeValue(forKey: "\(storageKey)")
                    defer { didChangeValue(forKey: "\(storageKey)") }
                    setPrimitiveValue(newValue.rawValue, forKey: "\(storageKey)")
                }
            }
        """
    }

    private func enumDefaultFallback(
        for attribute: NormalizedAttribute,
        enumKind: NormalizedEnumKind,
        entity: NormalizedEntity
    ) -> String {
        if let raw = attribute.defaultExpression?.trimmingCharacters(in: .whitespacesAndNewlines),
           !raw.isEmpty
        {
            // Leading-dot shorthand is rewritten as `Entity.Enum.case`; a
            // type-qualified expression (`Entity.Enum.case`) is used as-is.
            return raw.hasPrefix(".") ? "\(entity.swiftName).\(enumKind.typeName)\(raw)" : raw
        }
        // Without a default, fall back to a force-unwrap that will crash on
        // invalid stored values. Validation forces non-optional enums to
        // declare a default expression, so this branch should be unreachable
        // in practice.
        return "\(entity.swiftName).\(enumKind.typeName)(rawValue: raw ?? \(rawValueZero(rawType: enumKind.rawType)))!"
    }

    private func rawValueZero(rawType: String) -> String {
        switch rawType {
        case "String": "\"\""
        default: "0"
        }
    }

    private func renderBridge(entity: NormalizedEntity, schema: NormalizedSchema) -> String {
        let providerConformance = providerComputedProperties(entity: entity)
        let hydratingConversion = renderHydratingConversion(entity: entity, schema: schema)

        return """
        // Generated by slate-generator. Do not edit.

        @preconcurrency import CoreData
        import Foundation
        import \(schema.modelModule)
        import Slate
        import SlateSchema

        extension \(entity.mutableName): \(entity.swiftName).ManagedPropertyProviding {
        \(providerConformance)
        }

        extension \(entity.mutableName): SlateMutableObject {
            public typealias ImmutableObject = \(entity.swiftName)

            public var slateObject: \(entity.swiftName) {
                \(entity.swiftName)(managedObject: self)
            }
        }

        extension \(entity.mutableName): SlateRelationshipHydratingMutableObject {
        \(hydratingConversion)
        }

        """
    }

    private func renderSchema(_ schema: NormalizedSchema) -> String {
        let metadata = schema.entities.map(renderMetadata).joined(separator: ",\n")
        let modelEntities = schema.entities.map(renderEntityDescription).joined(separator: "\n\n")
        let modelRelationships = renderRelationshipDescriptions(schema: schema)
        let registrations = schema.entities.map { entity in
            let uniquenessLiteral = renderUniquenessLiteral(entity.uniqueness)
            return """
                    registry.register(
                        immutable: \(entity.swiftName).self,
                        mutable: \(entity.mutableName).self,
                        entityName: "\(entity.entityName)",
                        uniquenessConstraints: \(uniquenessLiteral)
                    )
            """
        }.joined(separator: "\n")

        return """
        // Generated by slate-generator. Do not edit.

        @preconcurrency import CoreData
        import Foundation
        import \(schema.modelModule)
        import Slate
        import SlateSchema

        public enum \(schema.schemaName): SlateSchema {
            public static let schemaIdentifier = "\(schema.schemaName)"
            public static let schemaFingerprint = "\(schema.schemaFingerprint)"

            public static let entities: [SlateEntityMetadata] = [
        \(metadata)
            ]

            public static func makeManagedObjectModel() throws -> NSManagedObjectModel {
        \(indent(modelEntities, spaces: 8))
        \(indent(modelRelationships, spaces: 8))

                let model = NSManagedObjectModel()
                model.entities = [
        \(schema.entities.map { "            \($0.swiftName.camelCase)Entity" }.joined(separator: ",\n"))
                ]
                return model
            }

            public static func registerTables(_ registry: inout SlateTableRegistry) {
        \(registrations)
            }
        }

        """
    }

    private func renderMetadata(entity: NormalizedEntity) -> String {
        let attributes = storageAttributes(for: entity).map { attribute in
            """
                    SlateAttributeMetadata(
                        swiftName: "\(attribute.swiftName)",
                        storageName: "\(attribute.storageName)",
                        swiftType: "\(attribute.swiftType)",
                        storageType: "\(attribute.storageType)",
                        optional: \(attribute.optional),
                        indexed: \(attribute.indexed)
                    )
            """
        }.joined(separator: ",\n")
        let relationships = entity.relationships.map { relationship in
            """
                    SlateRelationshipMetadata(
                        name: "\(relationship.name)",
                        kind: .\(relationship.kind),
                        destination: "\(relationship.destination)",
                        inverse: "\(relationship.inverse)",
                        deleteRule: .\(relationship.deleteRule),
                        ordered: \(relationship.ordered)
                    )
            """
        }.joined(separator: ",\n")

        return """
                SlateEntityMetadata(
                    immutableTypeName: "\(entity.swiftName)",
                    mutableTypeName: "\(entity.mutableName)",
                    entityName: "\(entity.entityName)",
                    attributes: [
        \(attributes)
                    ],
                    relationships: [
        \(relationships)
                    ]
                )
        """
    }

    private func renderEntityDescription(entity: NormalizedEntity) -> String {
        let storageAttributes = storageAttributes(for: entity)
        let attributeDescriptions = storageAttributes.map { attribute in
            let prefix = "\(entity.swiftName.camelCase)\(attribute.swiftName.upperCamelCase)Attribute"
            // Note: `NSAttributeDescription.isIndexed` was deprecated in
            // iOS 11 / macOS 10.13 in favor of
            // `NSEntityDescription.indexes`. We surface attribute-level
            // `@SlateAttribute(indexed: true)` flags by synthesizing a
            // single-element `NSFetchIndexDescription` per flagged
            // attribute in `renderFetchIndexes(entity:)`.
            var lines = [
                "let \(prefix) = NSAttributeDescription()",
                "\(prefix).name = \"\(attribute.storageName)\"",
                "\(prefix).attributeType = .\(coreDataAttributeType(for: attribute))",
                "\(prefix).isOptional = \(attribute.optional)",
            ]
            if let defaultLine = renderedDefaultValue(for: attribute, prefix: prefix, entity: entity) {
                lines.append(defaultLine)
            }
            return lines.map { "        \($0)" }.joined(separator: "\n")
        }.joined(separator: "\n\n")

        let propertyNames = storageAttributes.map {
            "\(entity.swiftName.camelCase)\($0.swiftName.upperCamelCase)Attribute"
        }.joined(separator: ", ")

        return """
        \(attributeDescriptions)

                let \(entity.swiftName.camelCase)Entity = NSEntityDescription()
                \(entity.swiftName.camelCase)Entity.name = "\(entity.entityName)"
                \(entity.swiftName.camelCase)Entity.managedObjectClassName = NSStringFromClass(\(entity.mutableName).self)
                \(entity.swiftName.camelCase)Entity.properties = [\(propertyNames)]
        \(renderUniquenessConstraints(entity: entity))
        \(renderFetchIndexes(entity: entity))
        """
    }

    private func renderUniquenessLiteral(_ uniqueness: [NormalizedUniqueness]) -> String {
        guard !uniqueness.isEmpty else { return "[]" }
        let inner = uniqueness.map { entry -> String in
            let names = entry.storageNames.map { "\"\($0)\"" }.joined(separator: ", ")
            return "[\(names)]"
        }.joined(separator: ", ")
        return "[\(inner)]"
    }

    private func renderUniquenessConstraints(entity: NormalizedEntity) -> String {
        guard !entity.uniqueness.isEmpty else {
            return ""
        }

        let constraints = entity.uniqueness.map { uniqueness in
            "[\(uniqueness.storageNames.map { "\"\($0)\"" }.joined(separator: ", "))]"
        }.joined(separator: ", ")

        return "\(entity.swiftName.camelCase)Entity.uniquenessConstraints = [\(constraints)]"
    }

    /// Single-attribute fetch indexes synthesized from
    /// `@SlateAttribute(indexed: true)` flags. The flag is preserved as
    /// metadata on `NormalizedAttribute.indexed`, but it no longer
    /// drives the deprecated `NSAttributeDescription.isIndexed`. Instead
    /// we promote it to a `NSFetchIndexDescription` here, skipping any
    /// attribute that's already covered by an entity-level index entry
    /// (so users who declared `@SlateEntity(indexes: [.index(\.x)])`
    /// don't end up with two indexes on the same column).
    private func synthesizedAttributeIndexes(entity: NormalizedEntity) -> [NormalizedIndex] {
        let coveredSingleColumn = Set(
            entity.indexes
                .filter { $0.storageNames.count == 1 }
                .map { $0.storageNames[0] }
        )
        let storageAttributes = storageAttributes(for: entity)
        return storageAttributes.compactMap { attribute -> NormalizedIndex? in
            guard attribute.indexed,
                  !coveredSingleColumn.contains(attribute.storageName)
            else {
                return nil
            }
            return NormalizedIndex(storageNames: [attribute.storageName])
        }
    }

    private func renderFetchIndexes(entity: NormalizedEntity) -> String {
        let allIndexes = entity.indexes + synthesizedAttributeIndexes(entity: entity)
        guard !allIndexes.isEmpty else {
            return ""
        }

        let entityVar = entity.swiftName.camelCase
        let isDescending = { (order: String) in order.lowercased() == "descending" }

        let indexes = allIndexes.enumerated().map { offset, index in
            let elementSetup = index.storageNames.enumerated().map { elementOffset, storageName in
                let elementVar = "\(entityVar)FetchIndex\(offset)Element\(elementOffset)"
                var lines = [
                    "let \(elementVar) = NSFetchIndexElementDescription(",
                    "    property: \(entityVar)Entity.propertiesByName[\"\(storageName)\"]!,",
                    "    collationType: .binary",
                    ")",
                ]
                if isDescending(index.order) {
                    lines.append("\(elementVar).isAscending = false")
                }
                return lines.joined(separator: "\n        ")
            }.joined(separator: "\n        ")

            let elementVars = index.storageNames.indices.map {
                "\(entityVar)FetchIndex\(offset)Element\($0)"
            }.joined(separator: ", ")

            return """
                \(elementSetup)
                let \(entityVar)FetchIndex\(offset) = NSFetchIndexDescription(
                    name: "\(entity.entityName)_index_\(offset)",
                    elements: [\(elementVars)]
                )
            """
        }.joined(separator: "\n")

        let indexNames = allIndexes.indices.map {
            "\(entityVar)FetchIndex\($0)"
        }.joined(separator: ", ")

        return """
        \(indexes)
                \(entityVar)Entity.indexes = [\(indexNames)]
        """
    }

    private func renderRelationshipDescriptions(schema: NormalizedSchema) -> String {
        let entityByName = Dictionary(uniqueKeysWithValues: schema.entities.map { ($0.swiftName, $0) })
        let declarations = schema.entities.flatMap { entity in
            entity.relationships.map { relationship in
                let variable = relationshipVariable(entity: entity, relationship: relationship)
                let destinationEntityVariable = entityByName[relationship.destination]?.swiftName.camelCase ?? relationship.destination.camelCase
                let minCount: Int
                let maxCount: Int
                if relationship.kind == "toOne" {
                    // toOne: minCount 0/1 by optional, maxCount always 1
                    minCount = relationship.optional ? 0 : 1
                    maxCount = 1
                } else {
                    minCount = relationship.minCount ?? 0
                    maxCount = relationship.maxCount ?? 0
                }
                return """
                let \(variable) = NSRelationshipDescription()
                \(variable).name = "\(relationship.name)"
                \(variable).destinationEntity = \(destinationEntityVariable)Entity
                \(variable).deleteRule = .\(coreDataDeleteRule(relationship.deleteRule))
                \(variable).isOptional = \(relationship.optional)
                \(variable).isOrdered = \(relationship.ordered)
                \(variable).minCount = \(minCount)
                \(variable).maxCount = \(maxCount)
                """
            }
        }.joined(separator: "\n\n")

        guard !declarations.isEmpty else {
            return ""
        }

        let inverseAssignments = schema.entities.flatMap { entity in
            entity.relationships.compactMap { relationship -> String? in
                guard let destination = entityByName[relationship.destination],
                      let inverse = destination.relationships.first(where: { $0.name == relationship.inverse })
                else {
                    return nil
                }
                return "\(relationshipVariable(entity: entity, relationship: relationship)).inverseRelationship = \(relationshipVariable(entity: destination, relationship: inverse))"
            }
        }.joined(separator: "\n")

        let propertyAssignments = schema.entities.map { entity in
            let attributeNames = storageAttributes(for: entity).map {
                "\(entity.swiftName.camelCase)\($0.swiftName.upperCamelCase)Attribute"
            }
            let relationshipNames = entity.relationships.map {
                relationshipVariable(entity: entity, relationship: $0)
            }
            return "\(entity.swiftName.camelCase)Entity.properties = [\((attributeNames + relationshipNames).joined(separator: ", "))]"
        }.joined(separator: "\n")

        return """
        \(declarations)

        \(inverseAssignments)

        \(propertyAssignments)
        """
    }

    private func relationshipVariable(entity: NormalizedEntity, relationship: NormalizedRelationship) -> String {
        "\(entity.swiftName.camelCase)\(relationship.name.upperCamelCase)Relationship"
    }

    private func coreDataDeleteRule(_ deleteRule: String) -> String {
        switch deleteRule {
        case "noAction": "noActionDeleteRule"
        case "cascade": "cascadeDeleteRule"
        case "deny": "denyDeleteRule"
        default: "nullifyDeleteRule"
        }
    }

    private func renderedDefaultValue(
        for attribute: NormalizedAttribute,
        prefix: String,
        entity: NormalizedEntity
    ) -> String? {
        guard let raw = attribute.defaultExpression?.trimmingCharacters(in: .whitespacesAndNewlines),
              !raw.isEmpty,
              raw != "nil"
        else {
            return nil
        }
        // Enum default written as `.case` (or fully qualified
        // `Entity.Enum.case`) is rendered as the enum's `.rawValue` so
        // Core Data persists the actual storage value.
        if let enumKind = attribute.enumKind {
            if raw.hasPrefix(".") {
                return "\(prefix).defaultValue = \(entity.swiftName).\(enumKind.typeName)\(raw).rawValue"
            }
            // Type-qualified expression: `Patient.Status.active`.
            let qualifiedPrefix = "\(entity.swiftName).\(enumKind.typeName)."
            if raw.hasPrefix(qualifiedPrefix) || raw.hasPrefix("\(enumKind.typeName).") {
                return "\(prefix).defaultValue = \(raw).rawValue"
            }
        }
        if isStringLiteral(raw) || isNumberLiteral(raw) || raw == "true" || raw == "false" {
            return "\(prefix).defaultValue = \(raw)"
        }
        return nil
    }

    private func isStringLiteral(_ text: String) -> Bool {
        text.count >= 2 && text.hasPrefix("\"") && text.hasSuffix("\"")
    }

    private func isNumberLiteral(_ text: String) -> Bool {
        guard let first = text.unicodeScalars.first else { return false }
        if !(CharacterSet.decimalDigits.contains(first) || first == "-") {
            return false
        }
        return Double(text) != nil
    }

    private func providerComputedProperties(entity: NormalizedEntity) -> String {
        let renamedAttributes = entity.attributes.compactMap { attribute in
            guard attribute.swiftName != attribute.storageName else {
                return nil
            }

            return """
                public var \(attribute.swiftName): \(attribute.swiftType) {
                    \(attribute.storageName)
                }
            """
        }.joined(separator: "\n")

        let embeddedProperties = entity.embedded.map { embedded in
            let assignments = embedded.attributes.map { attribute in
                "\(attribute.swiftName): \(attribute.storageName)"
            }.joined(separator: ",\n            ")

            if let presenceStorageName = embedded.presenceStorageName {
                return """
                    public var \(embedded.swiftName): \(entity.swiftName).\(embedded.swiftType)? {
                        guard \(presenceStorageName) else {
                            return nil
                        }
                        return \(entity.swiftName).\(embedded.swiftType)(
                            \(assignments)
                        )
                    }
                """
            }

            return """
                public var \(embedded.swiftName): \(entity.swiftName).\(embedded.swiftType) {
                    \(entity.swiftName).\(embedded.swiftType)(
                        \(assignments)
                    )
                }
            """
        }.joined(separator: "\n")

        return [renamedAttributes, embeddedProperties]
            .filter { !$0.isEmpty }
            .joined(separator: "\n")
    }

    private func renderHydratingConversion(entity: NormalizedEntity, schema: NormalizedSchema) -> String {
        let preflight = hydratingPreflightStatements(entity: entity)
            .map { "            \($0)" }
            .joined(separator: "\n")
        let arguments = hydratingInitializerArguments(entity: entity, schema: schema)
            .map { "                \($0)" }
            .joined(separator: ",\n")
        let body: String
        if preflight.isEmpty {
            body = """
                return \(entity.swiftName)(
            \(arguments)
                    )
            """
        } else {
            body = """
            \(preflight)
                return \(entity.swiftName)(
            \(arguments)
                    )
            """
        }

        return """
            public func slateObject(hydrating relationships: Set<String>) throws -> \(entity.swiftName) {
        \(body)
            }
        """
    }

    /// Generates `let <name> = try resolve...` statements for non-optional
    /// enum attributes so `slateObject(hydrating:)` can throw
    /// `SlateError.invalidStoredValue` when the stored raw value is missing
    /// or unmappable AND no default expression is available. Enums with a
    /// default expression fall back silently. Optional enums use the
    /// computed property's nil-fallback semantics and need no preflight.
    private func hydratingPreflightStatements(entity: NormalizedEntity) -> [String] {
        entity.attributes.compactMap { attribute -> String? in
            guard let enumKind = attribute.enumKind, !attribute.optional else {
                return nil
            }

            let qualifiedEnum = "\(entity.swiftName).\(enumKind.typeName)"
            let storageKey = attribute.storageName
            let rawType = enumKind.rawType
            let primitiveAccess = "primitiveValue(forKey: \"\(storageKey)\") as? \(rawType)"

            if let raw = attribute.defaultExpression?.trimmingCharacters(in: .whitespacesAndNewlines),
               !raw.isEmpty
            {
                // Accept either leading-dot shorthand (`.active`) or a
                // type-qualified expression (`Patient.Status.active`).
                let defaultValue = raw.hasPrefix(".") ? "\(qualifiedEnum)\(raw)" : raw
                return "let resolved\(attribute.swiftName.upperCamelCase): \(qualifiedEnum) = (\(primitiveAccess)).flatMap { \(qualifiedEnum)(rawValue: $0) } ?? \(defaultValue)"
            }

            return """
            guard let raw\(attribute.swiftName.upperCamelCase) = \(primitiveAccess) else {
                throw SlateError.invalidStoredValue(entity: "\(entity.entityName)", property: "\(storageKey)", valueDescription: "nil")
            }
            guard let resolved\(attribute.swiftName.upperCamelCase) = \(qualifiedEnum)(rawValue: raw\(attribute.swiftName.upperCamelCase)) else {
                throw SlateError.invalidStoredValue(entity: "\(entity.entityName)", property: "\(storageKey)", valueDescription: String(describing: raw\(attribute.swiftName.upperCamelCase)))
            }
            """
        }
    }

    private func hydratingInitializerArguments(entity: NormalizedEntity, schema: NormalizedSchema) -> [String] {
        let directAttributes = entity.attributes.map { attribute -> String in
            // Non-optional enums use the pre-flight resolved local; optional
            // enums and plain attributes are read directly through the
            // mutable class's typed accessor.
            if attribute.enumKind != nil, !attribute.optional {
                return "\(attribute.swiftName): resolved\(attribute.swiftName.upperCamelCase)"
            }
            return "\(attribute.swiftName): \(attribute.swiftName)"
        }
        let embedded = entity.embedded.map { embedded in
            "\(embedded.swiftName): \(embedded.swiftName)"
        }
        let relationships = entity.relationships.map { relationship in
            "\(relationship.name): \(relationshipHydrationExpression(relationship, schema: schema))"
        }
        return ["slateID: objectID"] + directAttributes + embedded + relationships
    }

    private func relationshipHydrationExpression(_ relationship: NormalizedRelationship, schema: NormalizedSchema) -> String {
        let destinationMutableName = schema.entities.first(where: { $0.swiftName == relationship.destination })?.mutableName ?? "Database\(relationship.destination)"
        if relationship.kind == "toOne" {
            return #"relationships.contains("\#(relationship.name)") ? \#(relationship.name)?.slateObject : nil"#
        }
        if relationship.ordered {
            return #"relationships.contains("\#(relationship.name)") ? (\#(relationship.name)?.array as? [\#(destinationMutableName)])?.map(\.slateObject) : nil"#
        }
        return #"relationships.contains("\#(relationship.name)") ? \#(relationship.name)?.map { $0.slateObject } : nil"#
    }

    private func storageAttributes(for entity: NormalizedEntity) -> [NormalizedAttribute] {
        entity.attributes + entity.embedded.flatMap { embedded in
            let presence = embedded.presenceStorageName.map { storageName in
                NormalizedAttribute(
                    swiftName: storageName,
                    storageName: storageName,
                    swiftType: "Bool",
                    storageType: "boolean",
                    optional: false
                )
            }
            return [presence].compactMap { $0 } + embedded.attributes.map { attribute in
                NormalizedAttribute(
                    swiftName: "\(embedded.swiftName)_\(attribute.swiftName)",
                    storageName: attribute.storageName,
                    swiftType: attribute.optional ? attribute.swiftType : "\(attribute.swiftType)?",
                    storageType: attribute.storageType,
                    optional: true,
                    indexed: attribute.indexed
                )
            }
        }
    }

    private func managedSwiftType(for attribute: NormalizedAttribute) -> String {
        attribute.swiftType
    }

    private func renderMutableRelationshipProperties(entity: NormalizedEntity, schema: NormalizedSchema) -> String {
        let entityByName = Dictionary(uniqueKeysWithValues: schema.entities.map { ($0.swiftName, $0) })
        return entity.relationships.map { relationship in
            let destinationMutableName = entityByName[relationship.destination]?.mutableName ?? "Database\(relationship.destination)"
            let type: String
            if relationship.kind == "toOne" {
                type = "\(destinationMutableName)?"
            } else if relationship.ordered {
                type = "NSOrderedSet?"
            } else {
                type = "Set<\(destinationMutableName)>?"
            }
            return "    @NSManaged public var \(relationship.name): \(type)"
        }.joined(separator: "\n")
    }

    private func coreDataAttributeType(for attribute: NormalizedAttribute) -> String {
        switch attribute.storageType {
        case "string", "rawRepresentable": "stringAttributeType"
        case "boolean": "booleanAttributeType"
        case "integer16": "integer16AttributeType"
        case "integer32": "integer32AttributeType"
        case "integer64": "integer64AttributeType"
        case "float": "floatAttributeType"
        case "double": "doubleAttributeType"
        case "decimal": "decimalAttributeType"
        case "date": "dateAttributeType"
        case "binary": "binaryDataAttributeType"
        case "uuid": "UUIDAttributeType"
        case "uri": "URIAttributeType"
        default: "stringAttributeType"
        }
    }

    private func indent(_ text: String, spaces: Int) -> String {
        let prefix = String(repeating: " ", count: spaces)
        return text.split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : prefix + $0 }
            .joined(separator: "\n")
    }
}

private extension String {
    var camelCase: String {
        prefix(1).lowercased() + dropFirst()
    }

    var upperCamelCase: String {
        prefix(1).uppercased() + dropFirst()
    }
}
